# private-al2023-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-eks-al2023
  region: us-west-2
  version: "1.32"  # Use latest supported EKS version

vpc:
  cidr: 10.0.0.0/16
  clusterEndpoints:
    publicAccess: false   # Private cluster
    privateAccess: true   # Enable private API endpoint
  nat:
    gateway: Single       # Required for private nodes to access internet

managedNodeGroups:
  - name: ng-al2023-xlarge
    amiFamily: AmazonLinux2023  # AL2023
    instanceType: m6i.xlarge    # Instance type
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    volumeSize: 50
    privateNetworking: true     # Nodes in private subnets
    labels:
      os: al2023
      nodeclass: managed
    tags:
      Environment: Production
    iam:
      withAddonPolicies:
        albIngress: true        # Enable ALB ingress permissions
        cloudWatch: true        # Enable CloudWatch logging
        ebs: true               # Enable EBS permissions
    ssh:  # Optional SSH access
      publicKeyPath: ~/.ssh/id_rsa.pub

# Optional: Fargate profile for serverless workloads
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system

# Optional: Cluster CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
